/*
 * AWS Identity and Access Management
 * <fullname>Identity and Access Management</fullname> <p>Identity and Access Management (IAM) is a web service for securely controlling access to Amazon Web Services services. With IAM, you can centrally manage users, security credentials such as access keys, and permissions that control which Amazon Web Services resources users and applications can access. For more information about IAM, see <a href=\"http://aws.amazon.com/iam/\">Identity and Access Management (IAM)</a> and the <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/\">Identity and Access Management User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2010-05-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EntityType;
import org.openapitools.client.model.PolicyUsageType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListEntitiesForPolicyRequest
 */
public class ListEntitiesForPolicyRequestTest {
    private final ListEntitiesForPolicyRequest model = new ListEntitiesForPolicyRequest();

    /**
     * Model tests for ListEntitiesForPolicyRequest
     */
    @Test
    public void testListEntitiesForPolicyRequest() {
        // TODO: test ListEntitiesForPolicyRequest
    }

    /**
     * Test the property 'policyArn'
     */
    @Test
    public void policyArnTest() {
        // TODO: test policyArn
    }

    /**
     * Test the property 'entityFilter'
     */
    @Test
    public void entityFilterTest() {
        // TODO: test entityFilter
    }

    /**
     * Test the property 'pathPrefix'
     */
    @Test
    public void pathPrefixTest() {
        // TODO: test pathPrefix
    }

    /**
     * Test the property 'policyUsageFilter'
     */
    @Test
    public void policyUsageFilterTest() {
        // TODO: test policyUsageFilter
    }

    /**
     * Test the property 'marker'
     */
    @Test
    public void markerTest() {
        // TODO: test marker
    }

    /**
     * Test the property 'maxItems'
     */
    @Test
    public void maxItemsTest() {
        // TODO: test maxItems
    }

}
