/*
 * AWS Identity and Access Management
 * <fullname>Identity and Access Management</fullname> <p>Identity and Access Management (IAM) is a web service for securely controlling access to Amazon Web Services services. With IAM, you can centrally manage users, security credentials such as access keys, and permissions that control which Amazon Web Services resources users and applications can access. For more information about IAM, see <a href=\"http://aws.amazon.com/iam/\">Identity and Access Management (IAM)</a> and the <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/\">Identity and Access Management User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2010-05-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PolicyVersion;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ManagedPolicyDetail
 */
public class ManagedPolicyDetailTest {
    private final ManagedPolicyDetail model = new ManagedPolicyDetail();

    /**
     * Model tests for ManagedPolicyDetail
     */
    @Test
    public void testManagedPolicyDetail() {
        // TODO: test ManagedPolicyDetail
    }

    /**
     * Test the property 'policyName'
     */
    @Test
    public void policyNameTest() {
        // TODO: test policyName
    }

    /**
     * Test the property 'policyId'
     */
    @Test
    public void policyIdTest() {
        // TODO: test policyId
    }

    /**
     * Test the property 'arn'
     */
    @Test
    public void arnTest() {
        // TODO: test arn
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'defaultVersionId'
     */
    @Test
    public void defaultVersionIdTest() {
        // TODO: test defaultVersionId
    }

    /**
     * Test the property 'attachmentCount'
     */
    @Test
    public void attachmentCountTest() {
        // TODO: test attachmentCount
    }

    /**
     * Test the property 'permissionsBoundaryUsageCount'
     */
    @Test
    public void permissionsBoundaryUsageCountTest() {
        // TODO: test permissionsBoundaryUsageCount
    }

    /**
     * Test the property 'isAttachable'
     */
    @Test
    public void isAttachableTest() {
        // TODO: test isAttachable
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'updateDate'
     */
    @Test
    public void updateDateTest() {
        // TODO: test updateDate
    }

    /**
     * Test the property 'policyVersionList'
     */
    @Test
    public void policyVersionListTest() {
        // TODO: test policyVersionList
    }

}
