/*
 * AWS Identity and Access Management
 * <fullname>Identity and Access Management</fullname> <p>Identity and Access Management (IAM) is a web service for securely controlling access to Amazon Web Services services. With IAM, you can centrally manage users, security credentials such as access keys, and permissions that control which Amazon Web Services resources users and applications can access. For more information about IAM, see <a href=\"http://aws.amazon.com/iam/\">Identity and Access Management (IAM)</a> and the <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/\">Identity and Access Management User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2010-05-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DeletionTaskFailureReasonType;
import org.openapitools.client.model.DeletionTaskStatusType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetServiceLinkedRoleDeletionStatusResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:26:34.090256+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class GetServiceLinkedRoleDeletionStatusResponse {
  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private DeletionTaskStatusType status;

  public static final String SERIALIZED_NAME_REASON = "Reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  @javax.annotation.Nullable
  private DeletionTaskFailureReasonType reason;

  public GetServiceLinkedRoleDeletionStatusResponse() {
  }

  public GetServiceLinkedRoleDeletionStatusResponse status(@javax.annotation.Nonnull DeletionTaskStatusType status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the deletion.
   * @return status
   */
  @javax.annotation.Nonnull
  public DeletionTaskStatusType getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull DeletionTaskStatusType status) {
    this.status = status;
  }


  public GetServiceLinkedRoleDeletionStatusResponse reason(@javax.annotation.Nullable DeletionTaskFailureReasonType reason) {
    this.reason = reason;
    return this;
  }

  /**
   * An object that contains details about the reason the deletion failed.
   * @return reason
   */
  @javax.annotation.Nullable
  public DeletionTaskFailureReasonType getReason() {
    return reason;
  }

  public void setReason(@javax.annotation.Nullable DeletionTaskFailureReasonType reason) {
    this.reason = reason;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetServiceLinkedRoleDeletionStatusResponse getServiceLinkedRoleDeletionStatusResponse = (GetServiceLinkedRoleDeletionStatusResponse) o;
    return Objects.equals(this.status, getServiceLinkedRoleDeletionStatusResponse.status) &&
        Objects.equals(this.reason, getServiceLinkedRoleDeletionStatusResponse.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetServiceLinkedRoleDeletionStatusResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("Status", "Reason"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("Status"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetServiceLinkedRoleDeletionStatusResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetServiceLinkedRoleDeletionStatusResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetServiceLinkedRoleDeletionStatusResponse is not found in the empty JSON string", GetServiceLinkedRoleDeletionStatusResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetServiceLinkedRoleDeletionStatusResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetServiceLinkedRoleDeletionStatusResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetServiceLinkedRoleDeletionStatusResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `Status`
      DeletionTaskStatusType.validateJsonElement(jsonObj.get("Status"));
      // validate the optional field `Reason`
      if (jsonObj.get("Reason") != null && !jsonObj.get("Reason").isJsonNull()) {
        DeletionTaskFailureReasonType.validateJsonElement(jsonObj.get("Reason"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetServiceLinkedRoleDeletionStatusResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetServiceLinkedRoleDeletionStatusResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetServiceLinkedRoleDeletionStatusResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetServiceLinkedRoleDeletionStatusResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetServiceLinkedRoleDeletionStatusResponse>() {
           @Override
           public void write(JsonWriter out, GetServiceLinkedRoleDeletionStatusResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetServiceLinkedRoleDeletionStatusResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetServiceLinkedRoleDeletionStatusResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetServiceLinkedRoleDeletionStatusResponse
   * @throws IOException if the JSON string is invalid with respect to GetServiceLinkedRoleDeletionStatusResponse
   */
  public static GetServiceLinkedRoleDeletionStatusResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetServiceLinkedRoleDeletionStatusResponse.class);
  }

  /**
   * Convert an instance of GetServiceLinkedRoleDeletionStatusResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

