/*
 * AWS Identity and Access Management
 * <fullname>Identity and Access Management</fullname> <p>Identity and Access Management (IAM) is a web service for securely controlling access to Amazon Web Services services. With IAM, you can centrally manage users, security credentials such as access keys, and permissions that control which Amazon Web Services resources users and applications can access. For more information about IAM, see <a href=\"http://aws.amazon.com/iam/\">Identity and Access Management (IAM)</a> and the <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/\">Identity and Access Management User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2010-05-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SAMLProviderListEntry;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Contains the response to a successful &lt;a&gt;ListSAMLProviders&lt;/a&gt; request. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:26:34.090256+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ListSAMLProvidersResponse {
  public static final String SERIALIZED_NAME_SA_M_L_PROVIDER_LIST = "SAMLProviderList";
  @SerializedName(SERIALIZED_NAME_SA_M_L_PROVIDER_LIST)
  @javax.annotation.Nullable
  private List<SAMLProviderListEntry> saMLProviderList;

  public ListSAMLProvidersResponse() {
  }

  public ListSAMLProvidersResponse saMLProviderList(@javax.annotation.Nullable List<SAMLProviderListEntry> saMLProviderList) {
    this.saMLProviderList = saMLProviderList;
    return this;
  }

  public ListSAMLProvidersResponse addSaMLProviderListItem(SAMLProviderListEntry saMLProviderListItem) {
    if (this.saMLProviderList == null) {
      this.saMLProviderList = new ArrayList<>();
    }
    this.saMLProviderList.add(saMLProviderListItem);
    return this;
  }

  /**
   * The list of SAML provider resource objects defined in IAM for this Amazon Web Services account.
   * @return saMLProviderList
   */
  @javax.annotation.Nullable
  public List<SAMLProviderListEntry> getSaMLProviderList() {
    return saMLProviderList;
  }

  public void setSaMLProviderList(@javax.annotation.Nullable List<SAMLProviderListEntry> saMLProviderList) {
    this.saMLProviderList = saMLProviderList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSAMLProvidersResponse listSAMLProvidersResponse = (ListSAMLProvidersResponse) o;
    return Objects.equals(this.saMLProviderList, listSAMLProvidersResponse.saMLProviderList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saMLProviderList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSAMLProvidersResponse {\n");
    sb.append("    saMLProviderList: ").append(toIndentedString(saMLProviderList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("SAMLProviderList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListSAMLProvidersResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListSAMLProvidersResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListSAMLProvidersResponse is not found in the empty JSON string", ListSAMLProvidersResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListSAMLProvidersResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListSAMLProvidersResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("SAMLProviderList") != null && !jsonObj.get("SAMLProviderList").isJsonNull()) {
        JsonArray jsonArraysaMLProviderList = jsonObj.getAsJsonArray("SAMLProviderList");
        if (jsonArraysaMLProviderList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("SAMLProviderList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `SAMLProviderList` to be an array in the JSON string but got `%s`", jsonObj.get("SAMLProviderList").toString()));
          }

          // validate the optional field `SAMLProviderList` (array)
          for (int i = 0; i < jsonArraysaMLProviderList.size(); i++) {
            SAMLProviderListEntry.validateJsonElement(jsonArraysaMLProviderList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListSAMLProvidersResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListSAMLProvidersResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListSAMLProvidersResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListSAMLProvidersResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ListSAMLProvidersResponse>() {
           @Override
           public void write(JsonWriter out, ListSAMLProvidersResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListSAMLProvidersResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListSAMLProvidersResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListSAMLProvidersResponse
   * @throws IOException if the JSON string is invalid with respect to ListSAMLProvidersResponse
   */
  public static ListSAMLProvidersResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListSAMLProvidersResponse.class);
  }

  /**
   * Convert an instance of ListSAMLProvidersResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

