/*
 * AWS Identity and Access Management
 * <fullname>Identity and Access Management</fullname> <p>Identity and Access Management (IAM) is a web service for securely controlling access to Amazon Web Services services. With IAM, you can centrally manage users, security credentials such as access keys, and permissions that control which Amazon Web Services resources users and applications can access. For more information about IAM, see <a href=\"http://aws.amazon.com/iam/\">Identity and Access Management (IAM)</a> and the <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/\">Identity and Access Management User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2010-05-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Tag;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * &lt;p&gt;Contains information about a managed policy.&lt;/p&gt; &lt;p&gt;This data type is used as a response element in the &lt;a&gt;CreatePolicy&lt;/a&gt;, &lt;a&gt;GetPolicy&lt;/a&gt;, and &lt;a&gt;ListPolicies&lt;/a&gt; operations. &lt;/p&gt; &lt;p&gt;For more information about managed policies, refer to &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/IAM/latest/UserGuide/policies-managed-vs-inline.html\&quot;&gt;Managed policies and inline policies&lt;/a&gt; in the &lt;i&gt;IAM User Guide&lt;/i&gt;. &lt;/p&gt;
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:26:34.090256+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class Policy {
  public static final String SERIALIZED_NAME_POLICY_NAME = "PolicyName";
  @SerializedName(SERIALIZED_NAME_POLICY_NAME)
  @javax.annotation.Nullable
  private String policyName;

  public static final String SERIALIZED_NAME_POLICY_ID = "PolicyId";
  @SerializedName(SERIALIZED_NAME_POLICY_ID)
  @javax.annotation.Nullable
  private String policyId;

  public static final String SERIALIZED_NAME_ARN = "Arn";
  @SerializedName(SERIALIZED_NAME_ARN)
  @javax.annotation.Nullable
  private String arn;

  public static final String SERIALIZED_NAME_PATH = "Path";
  @SerializedName(SERIALIZED_NAME_PATH)
  @javax.annotation.Nullable
  private String path;

  public static final String SERIALIZED_NAME_DEFAULT_VERSION_ID = "DefaultVersionId";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VERSION_ID)
  @javax.annotation.Nullable
  private String defaultVersionId;

  public static final String SERIALIZED_NAME_ATTACHMENT_COUNT = "AttachmentCount";
  @SerializedName(SERIALIZED_NAME_ATTACHMENT_COUNT)
  @javax.annotation.Nullable
  private Integer attachmentCount;

  public static final String SERIALIZED_NAME_PERMISSIONS_BOUNDARY_USAGE_COUNT = "PermissionsBoundaryUsageCount";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS_BOUNDARY_USAGE_COUNT)
  @javax.annotation.Nullable
  private Integer permissionsBoundaryUsageCount;

  public static final String SERIALIZED_NAME_IS_ATTACHABLE = "IsAttachable";
  @SerializedName(SERIALIZED_NAME_IS_ATTACHABLE)
  @javax.annotation.Nullable
  private Boolean isAttachable;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_CREATE_DATE = "CreateDate";
  @SerializedName(SERIALIZED_NAME_CREATE_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime createDate;

  public static final String SERIALIZED_NAME_UPDATE_DATE = "UpdateDate";
  @SerializedName(SERIALIZED_NAME_UPDATE_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime updateDate;

  public static final String SERIALIZED_NAME_TAGS = "Tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<Tag> tags;

  public Policy() {
  }

  public Policy policyName(@javax.annotation.Nullable String policyName) {
    this.policyName = policyName;
    return this;
  }

  /**
   * The friendly name (not ARN) identifying the policy.
   * @return policyName
   */
  @javax.annotation.Nullable
  public String getPolicyName() {
    return policyName;
  }

  public void setPolicyName(@javax.annotation.Nullable String policyName) {
    this.policyName = policyName;
  }


  public Policy policyId(@javax.annotation.Nullable String policyId) {
    this.policyId = policyId;
    return this;
  }

  /**
   * &lt;p&gt;The stable and unique string identifying the policy.&lt;/p&gt; &lt;p&gt;For more information about IDs, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html\&quot;&gt;IAM identifiers&lt;/a&gt; in the &lt;i&gt;IAM User Guide&lt;/i&gt;.&lt;/p&gt;
   * @return policyId
   */
  @javax.annotation.Nullable
  public String getPolicyId() {
    return policyId;
  }

  public void setPolicyId(@javax.annotation.Nullable String policyId) {
    this.policyId = policyId;
  }


  public Policy arn(@javax.annotation.Nullable String arn) {
    this.arn = arn;
    return this;
  }

  /**
   * &lt;p&gt;The Amazon Resource Name (ARN). ARNs are unique identifiers for Amazon Web Services resources.&lt;/p&gt; &lt;p&gt;For more information about ARNs, go to &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html\&quot;&gt;Amazon Resource Names (ARNs)&lt;/a&gt; in the &lt;i&gt;Amazon Web Services General Reference&lt;/i&gt;. &lt;/p&gt;
   * @return arn
   */
  @javax.annotation.Nullable
  public String getArn() {
    return arn;
  }

  public void setArn(@javax.annotation.Nullable String arn) {
    this.arn = arn;
  }


  public Policy path(@javax.annotation.Nullable String path) {
    this.path = path;
    return this;
  }

  /**
   * &lt;p&gt;The path to the policy.&lt;/p&gt; &lt;p&gt;For more information about paths, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html\&quot;&gt;IAM identifiers&lt;/a&gt; in the &lt;i&gt;IAM User Guide&lt;/i&gt;.&lt;/p&gt;
   * @return path
   */
  @javax.annotation.Nullable
  public String getPath() {
    return path;
  }

  public void setPath(@javax.annotation.Nullable String path) {
    this.path = path;
  }


  public Policy defaultVersionId(@javax.annotation.Nullable String defaultVersionId) {
    this.defaultVersionId = defaultVersionId;
    return this;
  }

  /**
   * The identifier for the version of the policy that is set as the default version.
   * @return defaultVersionId
   */
  @javax.annotation.Nullable
  public String getDefaultVersionId() {
    return defaultVersionId;
  }

  public void setDefaultVersionId(@javax.annotation.Nullable String defaultVersionId) {
    this.defaultVersionId = defaultVersionId;
  }


  public Policy attachmentCount(@javax.annotation.Nullable Integer attachmentCount) {
    this.attachmentCount = attachmentCount;
    return this;
  }

  /**
   * The number of entities (users, groups, and roles) that the policy is attached to.
   * @return attachmentCount
   */
  @javax.annotation.Nullable
  public Integer getAttachmentCount() {
    return attachmentCount;
  }

  public void setAttachmentCount(@javax.annotation.Nullable Integer attachmentCount) {
    this.attachmentCount = attachmentCount;
  }


  public Policy permissionsBoundaryUsageCount(@javax.annotation.Nullable Integer permissionsBoundaryUsageCount) {
    this.permissionsBoundaryUsageCount = permissionsBoundaryUsageCount;
    return this;
  }

  /**
   * &lt;p&gt;The number of entities (users and roles) for which the policy is used to set the permissions boundary. &lt;/p&gt; &lt;p&gt;For more information about permissions boundaries, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html\&quot;&gt;Permissions boundaries for IAM identities &lt;/a&gt; in the &lt;i&gt;IAM User Guide&lt;/i&gt;.&lt;/p&gt;
   * @return permissionsBoundaryUsageCount
   */
  @javax.annotation.Nullable
  public Integer getPermissionsBoundaryUsageCount() {
    return permissionsBoundaryUsageCount;
  }

  public void setPermissionsBoundaryUsageCount(@javax.annotation.Nullable Integer permissionsBoundaryUsageCount) {
    this.permissionsBoundaryUsageCount = permissionsBoundaryUsageCount;
  }


  public Policy isAttachable(@javax.annotation.Nullable Boolean isAttachable) {
    this.isAttachable = isAttachable;
    return this;
  }

  /**
   * Specifies whether the policy can be attached to an IAM user, group, or role.
   * @return isAttachable
   */
  @javax.annotation.Nullable
  public Boolean getIsAttachable() {
    return isAttachable;
  }

  public void setIsAttachable(@javax.annotation.Nullable Boolean isAttachable) {
    this.isAttachable = isAttachable;
  }


  public Policy description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * &lt;p&gt;A friendly description of the policy.&lt;/p&gt; &lt;p&gt;This element is included in the response to the &lt;a&gt;GetPolicy&lt;/a&gt; operation. It is not included in the response to the &lt;a&gt;ListPolicies&lt;/a&gt; operation. &lt;/p&gt;
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public Policy createDate(@javax.annotation.Nullable OffsetDateTime createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * The date and time, in &lt;a href&#x3D;\&quot;http://www.iso.org/iso/iso8601\&quot;&gt;ISO 8601 date-time format&lt;/a&gt;, when the policy was created.
   * @return createDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreateDate() {
    return createDate;
  }

  public void setCreateDate(@javax.annotation.Nullable OffsetDateTime createDate) {
    this.createDate = createDate;
  }


  public Policy updateDate(@javax.annotation.Nullable OffsetDateTime updateDate) {
    this.updateDate = updateDate;
    return this;
  }

  /**
   * &lt;p&gt;The date and time, in &lt;a href&#x3D;\&quot;http://www.iso.org/iso/iso8601\&quot;&gt;ISO 8601 date-time format&lt;/a&gt;, when the policy was last updated.&lt;/p&gt; &lt;p&gt;When a policy has only one version, this field contains the date and time when the policy was created. When a policy has more than one version, this field contains the date and time when the most recent policy version was created.&lt;/p&gt;
   * @return updateDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(@javax.annotation.Nullable OffsetDateTime updateDate) {
    this.updateDate = updateDate;
  }


  public Policy tags(@javax.annotation.Nullable List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public Policy addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * A list of tags that are attached to the instance profile. For more information about tagging, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html\&quot;&gt;Tagging IAM resources&lt;/a&gt; in the &lt;i&gt;IAM User Guide&lt;/i&gt;.
   * @return tags
   */
  @javax.annotation.Nullable
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<Tag> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Policy policy = (Policy) o;
    return Objects.equals(this.policyName, policy.policyName) &&
        Objects.equals(this.policyId, policy.policyId) &&
        Objects.equals(this.arn, policy.arn) &&
        Objects.equals(this.path, policy.path) &&
        Objects.equals(this.defaultVersionId, policy.defaultVersionId) &&
        Objects.equals(this.attachmentCount, policy.attachmentCount) &&
        Objects.equals(this.permissionsBoundaryUsageCount, policy.permissionsBoundaryUsageCount) &&
        Objects.equals(this.isAttachable, policy.isAttachable) &&
        Objects.equals(this.description, policy.description) &&
        Objects.equals(this.createDate, policy.createDate) &&
        Objects.equals(this.updateDate, policy.updateDate) &&
        Objects.equals(this.tags, policy.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyName, policyId, arn, path, defaultVersionId, attachmentCount, permissionsBoundaryUsageCount, isAttachable, description, createDate, updateDate, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Policy {\n");
    sb.append("    policyName: ").append(toIndentedString(policyName)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    arn: ").append(toIndentedString(arn)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    defaultVersionId: ").append(toIndentedString(defaultVersionId)).append("\n");
    sb.append("    attachmentCount: ").append(toIndentedString(attachmentCount)).append("\n");
    sb.append("    permissionsBoundaryUsageCount: ").append(toIndentedString(permissionsBoundaryUsageCount)).append("\n");
    sb.append("    isAttachable: ").append(toIndentedString(isAttachable)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    updateDate: ").append(toIndentedString(updateDate)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("PolicyName", "PolicyId", "Arn", "Path", "DefaultVersionId", "AttachmentCount", "PermissionsBoundaryUsageCount", "IsAttachable", "Description", "CreateDate", "UpdateDate", "Tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Policy
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Policy.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Policy is not found in the empty JSON string", Policy.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Policy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Policy` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("PolicyName") != null && !jsonObj.get("PolicyName").isJsonNull()) && !jsonObj.get("PolicyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `PolicyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("PolicyName").toString()));
      }
      if ((jsonObj.get("PolicyId") != null && !jsonObj.get("PolicyId").isJsonNull()) && !jsonObj.get("PolicyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `PolicyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("PolicyId").toString()));
      }
      if ((jsonObj.get("Arn") != null && !jsonObj.get("Arn").isJsonNull()) && !jsonObj.get("Arn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Arn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Arn").toString()));
      }
      if ((jsonObj.get("Path") != null && !jsonObj.get("Path").isJsonNull()) && !jsonObj.get("Path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Path").toString()));
      }
      if ((jsonObj.get("DefaultVersionId") != null && !jsonObj.get("DefaultVersionId").isJsonNull()) && !jsonObj.get("DefaultVersionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DefaultVersionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DefaultVersionId").toString()));
      }
      if ((jsonObj.get("Description") != null && !jsonObj.get("Description").isJsonNull()) && !jsonObj.get("Description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Description").toString()));
      }
      if (jsonObj.get("Tags") != null && !jsonObj.get("Tags").isJsonNull()) {
        JsonArray jsonArraytags = jsonObj.getAsJsonArray("Tags");
        if (jsonArraytags != null) {
          // ensure the json data is an array
          if (!jsonObj.get("Tags").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `Tags` to be an array in the JSON string but got `%s`", jsonObj.get("Tags").toString()));
          }

          // validate the optional field `Tags` (array)
          for (int i = 0; i < jsonArraytags.size(); i++) {
            Tag.validateJsonElement(jsonArraytags.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Policy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Policy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Policy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Policy.class));

       return (TypeAdapter<T>) new TypeAdapter<Policy>() {
           @Override
           public void write(JsonWriter out, Policy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Policy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Policy given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Policy
   * @throws IOException if the JSON string is invalid with respect to Policy
   */
  public static Policy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Policy.class);
  }

  /**
   * Convert an instance of Policy to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

