/*
 * AWS Identity and Access Management
 * <fullname>Identity and Access Management</fullname> <p>Identity and Access Management (IAM) is a web service for securely controlling access to Amazon Web Services services. With IAM, you can centrally manage users, security credentials such as access keys, and permissions that control which Amazon Web Services resources users and applications can access. For more information about IAM, see <a href=\"http://aws.amazon.com/iam/\">Identity and Access Management (IAM)</a> and the <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/\">Identity and Access Management User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2010-05-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.StatusType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * &lt;p&gt;Contains information about an SSH public key.&lt;/p&gt; &lt;p&gt;This data type is used as a response element in the &lt;a&gt;GetSSHPublicKey&lt;/a&gt; and &lt;a&gt;UploadSSHPublicKey&lt;/a&gt; operations. &lt;/p&gt;
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:26:34.090256+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class SSHPublicKey {
  public static final String SERIALIZED_NAME_USER_NAME = "UserName";
  @SerializedName(SERIALIZED_NAME_USER_NAME)
  @javax.annotation.Nonnull
  private String userName;

  public static final String SERIALIZED_NAME_SS_H_PUBLIC_KEY_ID = "SSHPublicKeyId";
  @SerializedName(SERIALIZED_NAME_SS_H_PUBLIC_KEY_ID)
  @javax.annotation.Nonnull
  private String ssHPublicKeyId;

  public static final String SERIALIZED_NAME_FINGERPRINT = "Fingerprint";
  @SerializedName(SERIALIZED_NAME_FINGERPRINT)
  @javax.annotation.Nonnull
  private String fingerprint;

  public static final String SERIALIZED_NAME_SS_H_PUBLIC_KEY_BODY = "SSHPublicKeyBody";
  @SerializedName(SERIALIZED_NAME_SS_H_PUBLIC_KEY_BODY)
  @javax.annotation.Nonnull
  private String ssHPublicKeyBody;

  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private StatusType status;

  public static final String SERIALIZED_NAME_UPLOAD_DATE = "UploadDate";
  @SerializedName(SERIALIZED_NAME_UPLOAD_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime uploadDate;

  public SSHPublicKey() {
  }

  public SSHPublicKey userName(@javax.annotation.Nonnull String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * The name of the IAM user associated with the SSH public key.
   * @return userName
   */
  @javax.annotation.Nonnull
  public String getUserName() {
    return userName;
  }

  public void setUserName(@javax.annotation.Nonnull String userName) {
    this.userName = userName;
  }


  public SSHPublicKey ssHPublicKeyId(@javax.annotation.Nonnull String ssHPublicKeyId) {
    this.ssHPublicKeyId = ssHPublicKeyId;
    return this;
  }

  /**
   * The unique identifier for the SSH public key.
   * @return ssHPublicKeyId
   */
  @javax.annotation.Nonnull
  public String getSsHPublicKeyId() {
    return ssHPublicKeyId;
  }

  public void setSsHPublicKeyId(@javax.annotation.Nonnull String ssHPublicKeyId) {
    this.ssHPublicKeyId = ssHPublicKeyId;
  }


  public SSHPublicKey fingerprint(@javax.annotation.Nonnull String fingerprint) {
    this.fingerprint = fingerprint;
    return this;
  }

  /**
   * The MD5 message digest of the SSH public key.
   * @return fingerprint
   */
  @javax.annotation.Nonnull
  public String getFingerprint() {
    return fingerprint;
  }

  public void setFingerprint(@javax.annotation.Nonnull String fingerprint) {
    this.fingerprint = fingerprint;
  }


  public SSHPublicKey ssHPublicKeyBody(@javax.annotation.Nonnull String ssHPublicKeyBody) {
    this.ssHPublicKeyBody = ssHPublicKeyBody;
    return this;
  }

  /**
   * The SSH public key.
   * @return ssHPublicKeyBody
   */
  @javax.annotation.Nonnull
  public String getSsHPublicKeyBody() {
    return ssHPublicKeyBody;
  }

  public void setSsHPublicKeyBody(@javax.annotation.Nonnull String ssHPublicKeyBody) {
    this.ssHPublicKeyBody = ssHPublicKeyBody;
  }


  public SSHPublicKey status(@javax.annotation.Nonnull StatusType status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the SSH public key. &lt;code&gt;Active&lt;/code&gt; means that the key can be used for authentication with an CodeCommit repository. &lt;code&gt;Inactive&lt;/code&gt; means that the key cannot be used.
   * @return status
   */
  @javax.annotation.Nonnull
  public StatusType getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull StatusType status) {
    this.status = status;
  }


  public SSHPublicKey uploadDate(@javax.annotation.Nullable OffsetDateTime uploadDate) {
    this.uploadDate = uploadDate;
    return this;
  }

  /**
   * The date and time, in &lt;a href&#x3D;\&quot;http://www.iso.org/iso/iso8601\&quot;&gt;ISO 8601 date-time format&lt;/a&gt;, when the SSH public key was uploaded.
   * @return uploadDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUploadDate() {
    return uploadDate;
  }

  public void setUploadDate(@javax.annotation.Nullable OffsetDateTime uploadDate) {
    this.uploadDate = uploadDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SSHPublicKey ssHPublicKey = (SSHPublicKey) o;
    return Objects.equals(this.userName, ssHPublicKey.userName) &&
        Objects.equals(this.ssHPublicKeyId, ssHPublicKey.ssHPublicKeyId) &&
        Objects.equals(this.fingerprint, ssHPublicKey.fingerprint) &&
        Objects.equals(this.ssHPublicKeyBody, ssHPublicKey.ssHPublicKeyBody) &&
        Objects.equals(this.status, ssHPublicKey.status) &&
        Objects.equals(this.uploadDate, ssHPublicKey.uploadDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, ssHPublicKeyId, fingerprint, ssHPublicKeyBody, status, uploadDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SSHPublicKey {\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    ssHPublicKeyId: ").append(toIndentedString(ssHPublicKeyId)).append("\n");
    sb.append("    fingerprint: ").append(toIndentedString(fingerprint)).append("\n");
    sb.append("    ssHPublicKeyBody: ").append(toIndentedString(ssHPublicKeyBody)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uploadDate: ").append(toIndentedString(uploadDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("UserName", "SSHPublicKeyId", "Fingerprint", "SSHPublicKeyBody", "Status", "UploadDate"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("UserName", "SSHPublicKeyId", "Fingerprint", "SSHPublicKeyBody", "Status"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SSHPublicKey
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SSHPublicKey.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SSHPublicKey is not found in the empty JSON string", SSHPublicKey.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SSHPublicKey.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SSHPublicKey` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SSHPublicKey.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("UserName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `UserName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("UserName").toString()));
      }
      if (!jsonObj.get("SSHPublicKeyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `SSHPublicKeyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("SSHPublicKeyId").toString()));
      }
      if (!jsonObj.get("Fingerprint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Fingerprint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Fingerprint").toString()));
      }
      if (!jsonObj.get("SSHPublicKeyBody").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `SSHPublicKeyBody` to be a primitive type in the JSON string but got `%s`", jsonObj.get("SSHPublicKeyBody").toString()));
      }
      // validate the required field `Status`
      StatusType.validateJsonElement(jsonObj.get("Status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SSHPublicKey.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SSHPublicKey' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SSHPublicKey> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SSHPublicKey.class));

       return (TypeAdapter<T>) new TypeAdapter<SSHPublicKey>() {
           @Override
           public void write(JsonWriter out, SSHPublicKey value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SSHPublicKey read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SSHPublicKey given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SSHPublicKey
   * @throws IOException if the JSON string is invalid with respect to SSHPublicKey
   */
  public static SSHPublicKey fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SSHPublicKey.class);
  }

  /**
   * Convert an instance of SSHPublicKey to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

