/*
 * AWS Identity and Access Management
 * <fullname>Identity and Access Management</fullname> <p>Identity and Access Management (IAM) is a web service for securely controlling access to Amazon Web Services services. With IAM, you can centrally manage users, security credentials such as access keys, and permissions that control which Amazon Web Services resources users and applications can access. For more information about IAM, see <a href=\"http://aws.amazon.com/iam/\">Identity and Access Management (IAM)</a> and the <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/\">Identity and Access Management User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2010-05-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Tag;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TagOpenIDConnectProviderRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:26:34.090256+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class TagOpenIDConnectProviderRequest {
  public static final String SERIALIZED_NAME_OPEN_I_D_CONNECT_PROVIDER_ARN = "OpenIDConnectProviderArn";
  @SerializedName(SERIALIZED_NAME_OPEN_I_D_CONNECT_PROVIDER_ARN)
  @javax.annotation.Nonnull
  private String openIDConnectProviderArn;

  public static final String SERIALIZED_NAME_TAGS = "Tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nonnull
  private List<Tag> tags;

  public TagOpenIDConnectProviderRequest() {
  }

  public TagOpenIDConnectProviderRequest openIDConnectProviderArn(@javax.annotation.Nonnull String openIDConnectProviderArn) {
    this.openIDConnectProviderArn = openIDConnectProviderArn;
    return this;
  }

  /**
   * &lt;p&gt;The ARN of the OIDC identity provider in IAM to which you want to add tags.&lt;/p&gt; &lt;p&gt;This parameter allows (through its &lt;a href&#x3D;\&quot;http://wikipedia.org/wiki/regex\&quot;&gt;regex pattern&lt;/a&gt;) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+&#x3D;,.@-&lt;/p&gt;
   * @return openIDConnectProviderArn
   */
  @javax.annotation.Nonnull
  public String getOpenIDConnectProviderArn() {
    return openIDConnectProviderArn;
  }

  public void setOpenIDConnectProviderArn(@javax.annotation.Nonnull String openIDConnectProviderArn) {
    this.openIDConnectProviderArn = openIDConnectProviderArn;
  }


  public TagOpenIDConnectProviderRequest tags(@javax.annotation.Nonnull List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public TagOpenIDConnectProviderRequest addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * The list of tags that you want to attach to the OIDC identity provider in IAM. Each tag consists of a key name and an associated value.
   * @return tags
   */
  @javax.annotation.Nonnull
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nonnull List<Tag> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagOpenIDConnectProviderRequest tagOpenIDConnectProviderRequest = (TagOpenIDConnectProviderRequest) o;
    return Objects.equals(this.openIDConnectProviderArn, tagOpenIDConnectProviderRequest.openIDConnectProviderArn) &&
        Objects.equals(this.tags, tagOpenIDConnectProviderRequest.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(openIDConnectProviderArn, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagOpenIDConnectProviderRequest {\n");
    sb.append("    openIDConnectProviderArn: ").append(toIndentedString(openIDConnectProviderArn)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("OpenIDConnectProviderArn", "Tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("OpenIDConnectProviderArn", "Tags"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TagOpenIDConnectProviderRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TagOpenIDConnectProviderRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TagOpenIDConnectProviderRequest is not found in the empty JSON string", TagOpenIDConnectProviderRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TagOpenIDConnectProviderRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TagOpenIDConnectProviderRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TagOpenIDConnectProviderRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("OpenIDConnectProviderArn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `OpenIDConnectProviderArn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("OpenIDConnectProviderArn").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("Tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `Tags` to be an array in the JSON string but got `%s`", jsonObj.get("Tags").toString()));
      }

      JsonArray jsonArraytags = jsonObj.getAsJsonArray("Tags");
      // validate the required field `Tags` (array)
      for (int i = 0; i < jsonArraytags.size(); i++) {
        Tag.validateJsonElement(jsonArraytags.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TagOpenIDConnectProviderRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TagOpenIDConnectProviderRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TagOpenIDConnectProviderRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TagOpenIDConnectProviderRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TagOpenIDConnectProviderRequest>() {
           @Override
           public void write(JsonWriter out, TagOpenIDConnectProviderRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TagOpenIDConnectProviderRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TagOpenIDConnectProviderRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TagOpenIDConnectProviderRequest
   * @throws IOException if the JSON string is invalid with respect to TagOpenIDConnectProviderRequest
   */
  public static TagOpenIDConnectProviderRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TagOpenIDConnectProviderRequest.class);
  }

  /**
   * Convert an instance of TagOpenIDConnectProviderRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

